language: "perl"

perl:
  - "5.20"

install:
    - cpanm --notest -q Sparrow
    - sparrow plg install file-touch-smoke  
    - "(dzil authordeps --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest)"
    - "(dzil listdeps  --author --missing | grep -vP '[^\\w:]' | cpanm --quiet --notest)"

script: "export PERL5LIB=$PWD/lib && sparrow plg run file-touch-smoke"
